language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libacl1-dev
  - go get golang.org/x/lint/golint

before_script:
  - go vet ./...
  - golint ./...
  - go test -v ./...

script:
  - go install ./grafsy
